#!/system/bin/sh
#

# EXT4 FS
insmod /system/lib/modules/jbd2.ko
insmod /system/lib/modules/ext4.ko

# network
insmod /system/lib/modules/tun.ko
echo veno > /proc/sys/net/ipv4/tcp_congestion_control

# usb serial
insmod /system/lib/modules/cp210x.ko
insmod /system/lib/modules/pl2303.ko

# gamepads
insmod /system/lib/modules/xpad.ko
insmod /system/lib/modules/hid-gaff.ko
insmod /system/lib/modules/hid-pl.ko
insmod /system/lib/modules/hid-sony.ko